### ISSUE TITLE
Powers of -1

### ISSUE THREAD

**Issue by scheinerman** [JuliaMath/FastPow.jl#1]
Is it possible to have `@fastpow` treat powers of `-1` differently than other bases? Integer powers of `-1` appear in alternating sums. 

This is a case where the base is known but the exponent is not, so a different problem than the goal of `FastPower` (fixed, positive integer exponent).

It would be great if `(-1)^n` could be automatically translated into  `isodd(n) ? -1 : 1`.

**Comment by dlfivefifty** [comment]
I’m curious what the fastest way to do ` (-1)^n ` actually is

**Comment by oscardssmith** [comment]
For integer n, it's probably `fma(-2, n&1, 1)`

**Comment by dlfivefifty** [comment]
Appears to be (suspiciously) exactly the same as the `isodd` version:
```julia
julia> altn(n) = (-1)^n;

julia> altn_isodd(n) = isodd(n) ? -1 : 1;

julia> altn_fma(n) = fma(-2, n&1, 1);

julia> @btime altn(5)
  1.982 ns (0 allocations: 0 bytes)
-1

julia> @btime altn(6)
  3.457 ns (0 allocations: 0 bytes)
1

julia> @btime altn_isodd(5)
  0.033 ns (0 allocations: 0 bytes)
-1

julia> @btime altn_isodd(6)
  0.033 ns (0 allocations: 0 bytes)
1

julia> @btime altn_fma(5)
  0.033 ns (0 allocations: 0 bytes)
-1

julia> @btime altn_fma(6)
  0.033 ns (0 allocations: 0 bytes)
1

```

**Comment by KristofferC** [comment]
Sub ns timings mean the whole computation got constant folded away.

**Comment by dlfivefifty** [comment]
Good point... (bizarre `altn(6)` is slower than `altn(5)`....). Here are alternative timings showing the fastest depends on whether `x` is even or odd:
```julia
julia> x = 5; @btime altn(x)
  17.218 ns (0 allocations: 0 bytes)
-1

julia> x = 6; @btime altn(x)
  15.902 ns (0 allocations: 0 bytes)
1

julia> x = 5; @btime altn_isodd(x)
  13.832 ns (0 allocations: 0 bytes)
-1

julia> x = 6; @btime altn_isodd(x)
  14.590 ns (0 allocations: 0 bytes)
1

julia> x = 5; @btime altn_fma(x)
  14.407 ns (0 allocations: 0 bytes)
-1

julia> x = 6; @btime altn_fma(x)
  13.830 ns (0 allocations: 0 bytes)
1
```

I feel like there should be some clever bitmask solution that is even faster...

**Comment by scheinerman** [comment]
I also tried `Bool(n&1) ? -1 : 1`. I'm also interested in larger values of `n` where the difference between this and `(-1)^n` is more pronounced. This happens in longer, alternating sums.

**Comment by dlfivefifty** [comment]
Surely the computational cost is independent of `n`... `iseven(n)` should only inspect the last bit

**Comment by scheinerman** [comment]
> Surely the computational cost is independent of `n`... `iseven(n)` should only inspect the last bit

Yes, but the time to compute `(-1)^n` depends on `n`. That's all I meant.

**Comment by KristofferC** [comment]
> I feel like there should be some clever bitmask solution that is even faster...

Your benchmarks above are completely dominated by the fact that `x` is a non-constant. You can't really micro benchmark something like `altn_fma` that basically does 1 or 2 instructions. The time it would take in real code would be dominated by other factors.

**Comment by dlfivefifty** [comment]
> The time it would take in real code would be dominated by other factors.

Yes of course it's just a hypothetical question, but it's a common operation so it would be nice to have a "canonical" implementation, which for the sake of uniqueness should be the fastest one.

**Comment by scheinerman** [comment]
It'd be nice if the compiler automatically notice expressions of the form `(-1)^Int` and applied a speedy method.

**Comment by dlfivefifty** [comment]
> Yes, but the time to compute (-1)^n depends on n. That's all I meant.

Wow, you are right:
```julia
julia> @btime altn(100)
  5.754 ns (0 allocations: 0 bytes)
1

julia> @btime altn(1000)
  7.906 ns (0 allocations: 0 bytes)
1

julia> @btime altn(10000)
  9.815 ns (0 allocations: 0 bytes)
1

julia> @btime altn(100000)
  11.710 ns (0 allocations: 0 bytes)
1
```

**Comment by dlfivefifty** [comment]
An example common usage is creating a vectors of alternating `1` and `-1`. Here `altn_isodd` is marginally the fastest, where `altn` is extremely slow:
```julia
julia> @btime altn.(1:100_000);
  4.019 ms (2 allocations: 781.33 KiB)

julia> @btime altn_isodd.(1:100_000);
  43.503 μs (2 allocations: 781.33 KiB)

julia> @btime altn_fma.(1:100_000);
  43.554 μs (2 allocations: 781.33 KiB)
```

**Comment by KristofferC** [comment]
`altn` just does a power of squaring method so will increase in time with `n`. It has some fast paths for different `p`:

https://github.com/JuliaLang/julia/blob/fb42ea57c24eb87d08d3021313d471359763cc62/base/intfuncs.jl#L257-L267

maybe it could be extended to different `x` as well.

**Comment by stevengj** [comment]
> It would be great if (-1)^n could be automatically translated into isodd(n) ? -1 : 1.

It would be possible to transform `(-1)^n` to `exp_minus1(n)`, and then define something like:
```jl
exp_minus1(p) = (-1)^p # fallback
exp_minus1(n::Integer) = isodd(n) ? -1 : 1
exp_minus1(p::Complex) = exp(-imag(p)*π) * cispi(real(p))

# requires Julia 1.7 for isodd of non-Integer types:
exp_minus1(p::Real) = isinteger(p) ? (isodd(p) ? -1 : 1) : throw(DomainError())
```

**Comment by stevengj** [comment]
> Integer powers of -1 appear in alternating sums.

If this is your application, you almost certainly do *not* want to do `(-1)^n`.   To evaluate series, you generally want to compute each term from the previous term.

For example, to compute `∑(-1)^n/n!`, you would do something like:
```jl
function myseries(Nterms)
    s = term = 1.0
    for n = 1:Nterms
        term = -term/n
        s += term
    end
    return s
end
````
(Or just call `exp(-1)`, of course.)

**Comment by stevengj** [comment]
We could also have fast paths for `2^x` and `10^x`.

**Comment by oscardssmith** [comment]
I think a lot of the problem is that `^`  is a bad abstraction. Const^x, x^const and x^y all have very different code that we want to generate, but since they all have the same name, we can't

**Comment by StefanKarpinski** [comment]
I wonder what a better abstraction would be. `pow(x, y)`, `pow(x)(y)` and `rpow(y)(x)`?

**Comment by scheinerman** [comment]
> > Integer powers of -1 appear in alternating sums.
> 
> If this is your application, you almost certainly do _not_ want to do `(-1)^n`. To evaluate series, you generally want to compute each term from the previous term.
> 
> For example, to compute `∑(-1)^n/n!`, you would do something like:
> 
> ```julia
> function myseries(Nterms)
>     s = term = 1.0
>     for n = 1:Nterms
>         term = -term/n
>         s += term
>     end
>     return s
> end
> ```
> 
> (Or just call `exp(-1)`, of course.)

You're right, of course, but as a mathematician I prefer having code that matches (as close as possible) the math formula. I think it makes it more readable.  And this approach won't work so well in a `sum(f(n) for n=0:100)` sort of expression.

**Comment by oscardssmith** [comment]
There's always `pow(val(x), y)`

**Comment by oscardssmith** [comment]
There's always `pow(val(x), y)`

**Comment by scheinerman** [comment]
Getting back to the original problem. Ideally, the Julia compiler would recognize `(-1)^Int` expressions and translate into something akin to `isodd(n) ? -1 : 0`. In the mean time, can `@fastpow` be modified to handle that? 

I am clueless about metaprogramming so I can't tell if what I'm asking makes sense. If this is infeasible, I should close this issue.

**Comment by KristofferC** [comment]
> Getting back to the original problem. Ideally, the Julia compiler would recognize (-1)^Int expressions and translate into something akin to isodd(n) ? -1 : 0.

Why does it have to be the compiler that does instead of just adding a check to the integer power function (around here https://github.com/JuliaLang/julia/blob/fb42ea57c24eb87d08d3021313d471359763cc62/base/intfuncs.jl#L257-L267)?

**Comment by scheinerman** [comment]
> > Getting back to the original problem. Ideally, the Julia compiler would recognize (-1)^Int expressions and translate into something akin to isodd(n) ? -1 : 0.
> 
> Why does it have to be the compiler that does instead of just adding a check to the integer power function (around here https://github.com/JuliaLang/julia/blob/fb42ea57c24eb87d08d3021313d471359763cc62/base/intfuncs.jl#L257-L267)?

That's fine. I'm not clear on how internals work.

**Comment by stevengj** [comment]
> Why does it have to be the compiler that does instead of just adding a check to the integer power function (around here

Adding a runtime check for this would slow down all integer powers for the sake of a rare optimization, no?

It’s certainly possible to do this optimization in the `@fastpow` macro, however, as I mentioned above.

**Comment by stevengj** [comment]
I've made a PR (#3) that optimizes this and a few other special cases.

**Comment by dlfivefifty** [comment]
> To evaluate series, you generally want to compute each term from the previous term

Surprisingly this is slower than the `isodd` version, though perhaps I got something wrong:
```julia
julia> v = Vector{Int}(undef,100_000);

julia> @btime broadcast!(altn_isodd, v, 1:100_000);
  19.409 μs (0 allocations: 0 bytes)

julia> function altn_vec!(v)
       term = one(eltype(v))
       @inbounds for k in axes(v,1)
           v[k] = term
           term = -term
       end
       v
   end
altn_vec! (generic function with 1 method)

julia> @btime altn_vec!(v);
  32.794 μs (0 allocations: 0 bytes)
```

**Comment by KristofferC** [comment]
> Adding a runtime check for this would slow down all integer powers for the sake of a rare optimization, no?

There are already a number of these checks being performed. If `x` is a literal (-1) it would probably constant propagate as well. Also, a correctly predicted non taken branch is for all intents and purposes free.
